- name: Add Docker-CE stable repo
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable Repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install containerd
  ansible.builtin.package:
    name: "https://download.docker.com/linux/centos/8/x86_64/stable/Packages/containerd.io-1.4.9-3.1.el8.x86_64.rpm"
    state: latest
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Add Docker-CE stable repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


- name: Install necessary packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop:
    - docker-ce
    - python3-pip
    - acl ### the acl package is a necessary requirement for ansible to work when switching from an unprivileged to an unprivileged user

- name: Start docker now
  systemd:
    name: docker
    state: started
    enabled: true

- name: install the requests module
  pip:
    name: ['requests', 'docker']
    executable: pip3


- name: Create the deployment user account
  ansible.builtin.user:
    name: deploy
    groups: docker

### Apparently this is not necessary as Ansible won't even start executing the playbook if it doesn't recognize a non-existent module
### This needs to be installed manually beforehand
#- name: check if community.docker is installed
#  shell: ansible-galaxy collection list | grep community.docker
#  register: IsCommunityDocker
#  changed_when: false
#
#- name: Install community docker_image module
#  command: ansible-galaxy collection install community.docker
#  when: IsCommunityDocker.rc !=0
