- name: Install necessary packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop:
    - docker-ce
    - acl ### the acl package is a necessary requirement for ansible to work when switching from an unprivileged to an unprivileged user

- name: Create the deployment user account 
  ansible.builtin.user:
    name: deploy
    groups: docker

### Apparently this is not necessary as Ansible won't even start executing the playbook if it doesn't recognize a non-existent module
### This needs to be installed manually beforehand
#- name: check if community.docker is installed
#  shell: ansible-galaxy collection list | grep community.docker
#  register: IsCommunityDocker
#  changed_when: false

- name: Install community docker_image module
  command: ansible-galaxy collection install community.docker
  when: IsCommunityDocker.rc !=0
